services:
  app:
    build: .
    container_name: streamlit_server
    ports:
      - 8501:8501
      - 5678:5678
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql+psycopg2://mluser:mlpass@db:5432/mlplayground
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mlplayground_db
    environment:
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpass
      POSTGRES_DB: mlplayground
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # New API service
  api:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://mluser:mlpass@db:5432/mlplayground
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
